#include "SystemConfig.h"

SystemConfig::SystemConfig() : m_darkTheme(true), m_simulationSpeedMs(1000) {}

SystemConfig& SystemConfig::getInstance() {
    static SystemConfig instance;
    return instance;
}

bool SystemConfig::isDarkTheme() const {
    return m_darkTheme;
}

void SystemConfig::setDarkTheme(bool dark) {
    if (m_darkTheme != dark) {
        m_darkTheme = dark;
        emit themeChanged(m_darkTheme);
    }
}

int SystemConfig::getSimulationSpeedMs() const {
    return m_simulationSpeedMs;
}

void SystemConfig::setSimulationSpeedMs(int speedMs) {
    m_simulationSpeedMs = speedMs;
}

QString SystemConfig::getStylesheet() const {
    if (m_darkTheme) {
        // Dark Mode Stylesheet (Slate / Blue Theme)
        return QString(
            "QWidget {"
            "    background-color: #0f172a;"
            "    color: #cbd5e1;"
            "    font-family: 'Segoe UI', 'Inter', Helvetica, Arial, sans-serif;"
            "    font-size: 13px;"
            "}"
            "QMainWindow {"
            "    background-color: #0b0f19;"
            "}"
            "QLabel {"
            "    background-color: transparent;"
            "    color: #f8fafc;"
            "}"
            "QLabel#TitleLabel {"
            "    font-size: 18px;"
            "    font-weight: bold;"
            "    color: #3b82f6;"
            "}"
            "QPushButton {"
            "    background-color: #2563eb;"
            "    color: #ffffff;"
            "    border: none;"
            "    border-radius: 6px;"
            "    padding: 8px 16px;"
            "    font-weight: 600;"
            "}"
            "QPushButton:hover {"
            "    background-color: #3b82f6;"
            "}"
            "QPushButton:pressed {"
            "    background-color: #1d4ed8;"
            "}"
            "QPushButton:disabled {"
            "    background-color: #334155;"
            "    color: #64748b;"
            "}"
            "QPushButton#SecondaryButton {"
            "    background-color: #334155;"
            "    color: #cbd5e1;"
            "}"
            "QPushButton#SecondaryButton:hover {"
            "    background-color: #475569;"
            "    color: #f8fafc;"
            "}"
            "QPushButton#DestructiveButton {"
            "    background-color: #dc2626;"
            "    color: #ffffff;"
            "}"
            "QPushButton#DestructiveButton:hover {"
            "    background-color: #ef4444;"
            "}"
            "QLineEdit, QSpinBox, QComboBox, QDoubleSpinBox {"
            "    background-color: #1e293b;"
            "    color: #f8fafc;"
            "    border: 1px solid #475569;"
            "    border-radius: 6px;"
            "    padding: 6px 12px;"
            "}"
            "QLineEdit:focus, QSpinBox:focus, QComboBox:focus {"
            "    border: 1px solid #3b82f6;"
            "}"
            "QComboBox::drop-down {"
            "    border: none;"
            "}"
            "QComboBox QAbstractItemView {"
            "    background-color: #1e293b;"
            "    border: 1px solid #475569;"
            "    selection-background-color: #2563eb;"
            "}"
            "QGroupBox {"
            "    border: 1px solid #334155;"
            "    border-radius: 8px;"
            "    margin-top: 12px;"
            "    padding-top: 16px;"
            "    font-weight: bold;"
            "    color: #94a3b8;"
            "}"
            "QGroupBox::title {"
            "    subcontrol-origin: margin;"
            "    subcontrol-position: top left;"
            "    left: 10px;"
            "    padding: 0 5px;"
            "}"
            "QTableWidget {"
            "    background-color: #1e293b;"
            "    gridline-color: #334155;"
            "    border: 1px solid #334155;"
            "    border-radius: 8px;"
            "    color: #f8fafc;"
            "}"
            "QTableWidget::item:selected {"
            "    background-color: #2563eb;"
            "    color: #ffffff;"
            "}"
            "QHeaderView::section {"
            "    background-color: #0f172a;"
            "    color: #94a3b8;"
            "    padding: 6px;"
            "    border: none;"
            "    border-bottom: 2px solid #334155;"
            "    font-weight: bold;"
            "}"
            "QScrollBar:vertical {"
            "    border: none;"
            "    background: #0f172a;"
            "    width: 10px;"
            "    margin: 0px;"
            "}"
            "QScrollBar::handle:vertical {"
            "    background: #475569;"
            "    min-height: 20px;"
            "    border-radius: 5px;"
            "}"
            "QScrollBar::handle:vertical:hover {"
            "    background: #64748b;"
            "}"
            "QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {"
            "    border: none;"
            "    background: none;"
            "}"
            "QListWidget {"
            "    background-color: #1e293b;"
            "    border: 1px solid #334155;"
            "    border-radius: 8px;"
            "    padding: 5px;"
            "}"
            "QListWidget::item {"
            "    padding: 8px;"
            "    border-radius: 4px;"
            "    color: #cbd5e1;"
            "}"
            "QListWidget::item:hover {"
            "    background-color: #334155;"
            "}"
            "QListWidget::item:selected {"
            "    background-color: #2563eb;"
            "    color: #ffffff;"
            "}"
            "QTabWidget::pane {"
            "    border: 1px solid #334155;"
            "    border-radius: 8px;"
            "    background-color: #1e293b;"
            "}"
            "QTabBar::tab {"
            "    background: #0f172a;"
            "    border: 1px solid #334155;"
            "    border-bottom-color: none;"
            "    border-top-left-radius: 6px;"
            "    border-top-right-radius: 6px;"
            "    padding: 8px 16px;"
            "    color: #cbd5e1;"
            "}"
            "QTabBar::tab:selected, QTabBar::tab:hover {"
            "    background: #1e293b;"
            "    color: #f8fafc;"
            "}"
            "QTabBar::tab:selected {"
            "    border-bottom: 2px solid #3b82f6;"
            "}"
        );
    } else {
        // Light Mode Stylesheet (Clean Corporate Academic Blue)
        return QString(
            "QWidget {"
            "    background-color: #f8fafc;"
            "    color: #334155;"
            "    font-family: 'Segoe UI', 'Inter', Helvetica, Arial, sans-serif;"
            "    font-size: 13px;"
            "}"
            "QMainWindow {"
            "    background-color: #f1f5f9;"
            "}"
            "QLabel {"
            "    background-color: transparent;"
            "    color: #0f172a;"
            "}"
            "QLabel#TitleLabel {"
            "    font-size: 18px;"
            "    font-weight: bold;"
            "    color: #1d4ed8;"
            "}"
            "QPushButton {"
            "    background-color: #2563eb;"
            "    color: #ffffff;"
            "    border: none;"
            "    border-radius: 6px;"
            "    padding: 8px 16px;"
            "    font-weight: 600;"
            "}"
            "QPushButton:hover {"
            "    background-color: #1d4ed8;"
            "}"
            "QPushButton:pressed {"
            "    background-color: #1e40af;"
            "}"
            "QPushButton:disabled {"
            "    background-color: #e2e8f0;"
            "    color: #94a3b8;"
            "}"
            "QPushButton#SecondaryButton {"
            "    background-color: #e2e8f0;"
            "    color: #334155;"
            "}"
            "QPushButton#SecondaryButton:hover {"
            "    background-color: #cbd5e1;"
            "    color: #0f172a;"
            "}"
            "QPushButton#DestructiveButton {"
            "    background-color: #dc2626;"
            "    color: #ffffff;"
            "}"
            "QPushButton#DestructiveButton:hover {"
            "    background-color: #b91c1c;"
            "}"
            "QLineEdit, QSpinBox, QComboBox, QDoubleSpinBox {"
            "    background-color: #ffffff;"
            "    color: #0f172a;"
            "    border: 1px solid #cbd5e1;"
            "    border-radius: 6px;"
            "    padding: 6px 12px;"
            "}"
            "QLineEdit:focus, QSpinBox:focus, QComboBox:focus {"
            "    border: 1px solid #2563eb;"
            "}"
            "QComboBox::drop-down {"
            "    border: none;"
            "}"
            "QComboBox QAbstractItemView {"
            "    background-color: #ffffff;"
            "    border: 1px solid #cbd5e1;"
            "    selection-background-color: #2563eb;"
            "}"
            "QGroupBox {"
            "    border: 1px solid #cbd5e1;"
            "    border-radius: 8px;"
            "    margin-top: 12px;"
            "    padding-top: 16px;"
            "    font-weight: bold;"
            "    color: #475569;"
            "}"
            "QGroupBox::title {"
            "    subcontrol-origin: margin;"
            "    subcontrol-position: top left;"
            "    left: 10px;"
            "    padding: 0 5px;"
            "}"
            "QTableWidget {"
            "    background-color: #ffffff;"
            "    gridline-color: #e2e8f0;"
            "    border: 1px solid #cbd5e1;"
            "    border-radius: 8px;"
            "    color: #0f172a;"
            "}"
            "QTableWidget::item:selected {"
            "    background-color: #2563eb;"
            "    color: #ffffff;"
            "}"
            "QHeaderView::section {"
            "    background-color: #f1f5f9;"
            "    color: #475569;"
            "    padding: 6px;"
            "    border: none;"
            "    border-bottom: 2px solid #cbd5e1;"
            "    font-weight: bold;"
            "}"
            "QScrollBar:vertical {"
            "    border: none;"
            "    background: #f1f5f9;"
            "    width: 10px;"
            "    margin: 0px;"
            "}"
            "QScrollBar::handle:vertical {"
            "    background: #cbd5e1;"
            "    min-height: 20px;"
            "    border-radius: 5px;"
            "}"
            "QScrollBar::handle:vertical:hover {"
            "    background: #94a3b8;"
            "}"
            "QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {"
            "    border: none;"
            "    background: none;"
            "}"
            "QListWidget {"
            "    background-color: #ffffff;"
            "    border: 1px solid #cbd5e1;"
            "    border-radius: 8px;"
            "    padding: 5px;"
            "}"
            "QListWidget::item {"
            "    padding: 8px;"
            "    border-radius: 4px;"
            "    color: #334155;"
            "}"
            "QListWidget::item:hover {"
            "    background-color: #f1f5f9;"
            "}"
            "QListWidget::item:selected {"
            "    background-color: #2563eb;"
            "    color: #ffffff;"
            "}"
            "QTabWidget::pane {"
            "    border: 1px solid #cbd5e1;"
            "    border-radius: 8px;"
            "    background-color: #ffffff;"
            "}"
            "QTabBar::tab {"
            "    background: #f1f5f9;"
            "    border: 1px solid #cbd5e1;"
            "    border-bottom-color: none;"
            "    border-top-left-radius: 6px;"
            "    border-top-right-radius: 6px;"
            "    padding: 8px 16px;"
            "    color: #475569;"
            "}"
            "QTabBar::tab:selected, QTabBar::tab:hover {"
            "    background: #ffffff;"
            "    color: #0f172a;"
            "}"
            "QTabBar::tab:selected {"
            "    border-bottom: 2px solid #2563eb;"
            "}"
        );
    }
}
